// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function DownloadFrpc(arg1:string):Promise<void>;

export function ExportPresetAsTomlBatch(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExportPresetToml(arg1:string,arg2:string):Promise<string>;

export function ExportToml(arg1:models.Server,arg2:Array<models.Service>):Promise<string>;

export function GetDataDir():Promise<string>;

export function GetFrpcVersion():Promise<string>;

export function GetRunningServers():Promise<Array<models.ServerRuntime>>;

export function GetServerLogs(arg1:string,arg2:string):Promise<Array<models.LogEntry>>;

export function GetServerUptime(arg1:string,arg2:string):Promise<number>;

export function ImportFrpFiles():Promise<Array<main.ImportResult>>;

export function ImportPresetFromToml():Promise<string>;

export function IsFrpcDownloaded():Promise<boolean>;

export function IsServerRunning(arg1:string,arg2:string):Promise<boolean>;

export function LoadAppConfig():Promise<string>;

export function SaveAppConfig(arg1:string):Promise<void>;

export function StartServer(arg1:string,arg2:string,arg3:models.Server,arg4:Array<models.Service>):Promise<void>;

export function StopServer(arg1:string,arg2:string):Promise<void>;
