// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadFrpc(arg1) {
  return window['go']['main']['App']['DownloadFrpc'](arg1);
}

export function ExportPresetAsToml(arg1, arg2) {
  return window['go']['main']['App']['ExportPresetAsToml'](arg1, arg2);
}

export function ExportPresetToml(arg1, arg2) {
  return window['go']['main']['App']['ExportPresetToml'](arg1, arg2);
}

export function ExportToml(arg1, arg2) {
  return window['go']['main']['App']['ExportToml'](arg1, arg2);
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetFrpcVersion() {
  return window['go']['main']['App']['GetFrpcVersion']();
}

export function GetRunningServers() {
  return window['go']['main']['App']['GetRunningServers']();
}

export function GetServerLogs(arg1, arg2) {
  return window['go']['main']['App']['GetServerLogs'](arg1, arg2);
}

export function GetServerUptime(arg1, arg2) {
  return window['go']['main']['App']['GetServerUptime'](arg1, arg2);
}

export function ImportFrpFiles() {
  return window['go']['main']['App']['ImportFrpFiles']();
}

export function ImportPresetFromToml() {
  return window['go']['main']['App']['ImportPresetFromToml']();
}

export function IsFrpcDownloaded() {
  return window['go']['main']['App']['IsFrpcDownloaded']();
}

export function IsServerRunning(arg1, arg2) {
  return window['go']['main']['App']['IsServerRunning'](arg1, arg2);
}

export function LoadAppConfig() {
  return window['go']['main']['App']['LoadAppConfig']();
}

export function SaveAppConfig(arg1) {
  return window['go']['main']['App']['SaveAppConfig'](arg1);
}

export function StartServer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartServer'](arg1, arg2, arg3, arg4);
}

export function StopServer(arg1, arg2) {
  return window['go']['main']['App']['StopServer'](arg1, arg2);
}
